# makefile for lab5
all: test.exe

test.exe: test.cpp Image.cpp Circle.cpp VotingData.cpp CircleDetection.cpp
	g++ -g -o test.exe test.cpp Image.cpp Circle.cpp VotingData.cpp CircleDetection.cpp -lm

